---
- name: Extract System Information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display OS Release
      debug:
        var: ansible_distribution + " " + ansible_distribution_version

    - name: Display Hostname
      debug:
        var: ansible_hostname

    - name: Display IPv4 Address
      debug:
        var: ansible_default_ipv4.address
